# Generated by Django 3.0.4 on 2021-02-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_products_cate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cate_name',
        ),
    ]
