# Generated by Django 3.0.4 on 2021-02-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='prod_quantity',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
