# Generated by Django 3.0.4 on 2021-02-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_otp_cust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_verify',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
