# Generated by Django 3.0.4 on 2021-02-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_customer_is_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_verify',
            field=models.BooleanField(default=0),
        ),
    ]
