# Generated by Django 3.0.4 on 2021-02-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210209_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Customer'),
        ),
    ]
