# Generated by Django 3.0.4 on 2021-02-13 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_receipt_receipt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
